apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: aviraj504/mern-social-web-2.0:latest
        env:
          - name: NODE_ENV
            value: development
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-password
          - name: MONGO_IP
            value: mongo-service
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: session-secret
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-initdb-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secrets
                key: mongo-initdb-root-password
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
  clusterIP: None
